server:
  servlet:
    context-path: /jimmy
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jimmy?characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 114514
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-config:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.jimmy.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表